build_from:
  # renovate: datasource=github-releases depName=open-webui/open-webui
  aarch64: ghcr.io/open-webui/open-webui:v0.6.14
  # renovate: datasource=github-releases depName=open-webui/open-webui
  amd64: ghcr.io/open-webui/open-webui:v0.6.14