name: "Open WebUI"
description: "Open WebUI is an extensible, self-hosted interface for AI that adapts to your workflow, all while operating entirely offline."
# renovate: datasource=github-releases depName=open-webui/open-webui
version: "0.6.16"
slug: "open-webui"
arch:
  - aarch64
  - amd64
url: https://openwebui.com
map:
  - type: addon_config
    read_only: False
    path: /app/backend/data
legacy: True
host_network: True
options:
  port: 8080
  env_vars: []
schema:
  port: port
  env_vars:
    - name: match(^[A-Z0-9_]+$)
      value: str
init: false
startup: application
